version: "3"
services:
  server:
    image: node:12.18.4
    working_dir: /code
    volumes:
      - type: bind
        source: ./api
        target: /code
    ports: 
      - 3000:3000
    
    environment: 
      - DB_NAME=posts_db
      - DB_CONNECTION=mongodb://pearlAndElwin:password@db:27017
    depends_on:
      - db
    command: bash -c "npm install && npm start"

  

  db:
    image: mongo:latest

    volumes:
      - "./db/seeds.js:/docker-entrypoint-initdb.d/seeds.js:ro"
      - data-volume:/data/db

    environment: 
      - MONGO_INITDB_ROOT_USERNAME=pearlAndElwin
      - MONGO_INITDB_DATABASE=posts_db
      - MONGO_INITDB_ROOT_PASSWORD=password
volumes:
    data-volume:

